spring:
  application:
    name: vehicle-web
  mvc:
    view:
      suffix: .html
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/static/
    suffix: .html

